import "~/styles/globals.css";

import { type Metadata } from "next";
import { Fraunces, Instrument_Sans } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { I18nProvider } from "~/app/_components/i18n-provider";
import { Navbar } from "~/app/_components/navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
});

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${fraunces.variable} ${instrumentSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <I18nProvider>
            <Navbar />
            <div className="pt-14">{children}</div>
          </I18nProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}


